---
workspace_path: "tmp"
skip_exists: false
max_image_dim: null
n_retrieval: 10
use_points_only: false

pose_estimation:
  max_error_point: 12.0
  max_error_line: 12.0
  weight_point: 1.0
  weight_line: 1.0
  max_iterations: 10000
  min_iterations: 100
  success_prob: 0.9999
  random_seed: true
  estimate_focal_length: false

_image_description:
  point_detection:
    method: "aliked-n16"
  line_detection:
    detector_method: "deeplsd"
    extractor_method: "wireframe"

_image_association:
  point_matcher:
    method: "aliked+lightglue"
  line_matcher:
    method: "gluestick"
